### PR TITLE
Cli backends

### PR DESCRIPTION
**Pull request by thomasmmitchell**
* Moved config into the CLI code. Wrote a wrapper around it that collects information about a backend.
* API code now takes a configured backend object instead of needing to load in a YAML file.
* Added `delete-backend` and `rename-backend` commands.
* -k can be specified to `create-backend` to have that backend always skip-ssl-validation (#174)
* `backends` now colors the current backend green
* `backends` will mark `-k`'d backends with a red `(insecure)`
* The config package now cleans up orphaned references to aliases (#312)
* tui tables now properly calculate column width when using non-printing characters and ansi escape colorization (#313)
* Wrote a test suite for the new config layout.

### CODE REVIEW

**Comment by thomasmmitchell** [comment]
Travis is catching an issue with me importing the wrong log library. Need a moment

**Comment by thomasmmitchell** [comment]
Good to review. Agent tests still not passing because of state on the auth branch. Should turn off that test suite until James can get back and actually recall what state it was left in.

**Comment by drnic** [comment]
@thomasmmitchell @xanderrman can you please add `ci/release_notes.md`?

**Comment by drnic** [comment]
The tests for the PR weren't passing - why was the PR merged?

screen shot 2017-09-07 at 7 20 42 am

**Comment by xanderrman** [comment]
I believe those failing tests are part of an unrelated issue that @thomasmmitchell mentioned above

**Comment by thomasmmitchell** [comment]
This is a development branch, and those agent tests don't touch this code at all. Those tests should probably be disabled until @jhunt returns, or somebody is actively working on the agent code

**Comment by jhunt** [comment]
I shall return...

**Pull request merged**
