### PR TITLE
[swift] New store plugin 'swift': for OpenStack Swift/Rackspace Cloud Files

### PR DESCRIPTION
**Pull request by drnic**
To dev/test this via `./bin/dev-setup`, replace:

```
echo "store=$store"
```

with:

```
store=$( $shieldcomm create store <<MEEP1 | $jqcomm .uuid
{
  "endpoint": "{\"auth_url\":\"https://identity.api.rackspacecloud.com/v2.0\",\"project_name\":\"xxx\",\"username\":\"xxx\",\"password\":\"xxx\",\"container\":\"bucket\",\"debug\":false}",
  "name": "DevSwift",
  "plugin": "swift",
  "summary": "Rackspace Swift objectstorage"
}
MEEP1 )
echo "store=$store"
```

### CODE REVIEW

**Comment by jhunt** [comment]
Can you vendor the openstack deps?

**Comment by drnic** [comment]
@jhunt done, thx for reminder

**Comment by drnic** [comment]
@jhunt bump

**Comment by jhunt** [comment]
It's on my radar for this week, don't you worry.

**Pull request merged**
