### PR TITLE
support MySQL (#184)

### PR DESCRIPTION
**Pull request by gogolok**
Based on the recent sqlx addition, we can now support MySQL/MariaDB as a backend.

- introduce MySQL driver github.com/go-sql-driver/mysql
- MySQL/MariaDB uses another schema than PostgreSQL. We moved the schema to different packages with same interfaces. #184 suggests we put it into the same functions. Can someone elaborate on that idea?
- the db.Connect method  appends sql_mode POSTGRESQL when not set to ensure that the operator "||" can be used to concatenate strings
- Can you clarify why the type 'text' gets used for certain status columns insteaf of varchar(X) for example? MySQL has trouble supporting `text DEFAULT 'default-value'`. This would simplify the differences in the schema.

### CODE REVIEW

**Comment by jhunt** [comment]
My concern with having the same logical schema in two different packages is that they will not be updated in parallel.  Perhaps this is just a pothole we have to deal with based on how Go works, but my initial thought was to switch inside the migration function, and run different queries based on targeted database engine.  i.e. for Postgres, do X, for MySQL, do Y.  This also means that we don't run the risk of having different schema versions for different backends when (for example) we have to tweak the MySQL schema only, and we bump the schema version -- does the PostgreSQL schema contain a weird, empty schema function for that version (since it was unaffected?)

TEXT was used to avoid placing arbitrary limits on column fields.  Switching to VARCHAR should be acceptable.

**Comment by karampok** [comment]
I agree that having two different schemas to be maintained in parallel,  is not ideal. 

Two different schemas came from the fact that we have
1. UUID types that exists in PostgreSQL, and not in MySQL (+ PRIMARY KEY)
2. the `text DEFAULT 'default-value'`, which is also not supported in MySQL
3. other variables (e.g. the InnoDB engine) that are only MySQL related

We thought it would be better option to keep the PostgreSQL schema/current workflow intact, and develop in parallel and independently introducing minimal changes. 

Do you think there will be cases when we will have to tweak only one of database schemas?
Different schema version per database type could also be an option.

On the other side, If we would like to merge them:
for the number 2 we could change it in general,  if that is ok with you,
for the number 3 we could enforce it in the DSN
for the UUID type is the question, we could do a custom function that translates the UUID to varchar(36) before the sql query, not perfect though. What do you think?

**Comment by jhunt** [comment]
I understand the rationale for two different schemas - different database engines need different things.  (This is one of the reasons we standardized on PostgreSQL to begin with; ORMs only net you so much).

My concern is that by maintaining the SQL in two different files, it becomes difficult to compare them for equivalence.  Can we do something like this instead?

```
package schema

// ...

func (s v1Schema) Deploy(db *DB) error {
  var err error
  switch db.Type {
  case "mysql":
    err = db.Exec(`CREATE TABLE schema_info (version INTEGER) ENGINE = InnoDB`)
  case "postgres":
    err = db.Exec(`CREATE TABLE schema_info (version INTEGER)`)
  default:
    err = fmt.Errorf("unsupported database type '%s'", db.Type)
  }
  if err != nil {
    return err
  } 
  // ...
}
```

**Comment by karampok** [comment]
okay, so basically you suggest that we have indeed two set of SQL statements if  needed (schema/migrations per database type), but located always in the same go file so we can easily compare and maintain them.  Yes this sound better for sure, we can also have single case statement if SQL statement applies to both types. @gogolok do you agree?

**Comment by gogolok** [comment]
Okay, will try that approach

**Comment by gogolok** [comment]
We've updated the sources:

- The MySQL schemas are within the schema version files.
- The special requirements on the DSN (sql_mode POSTRGESQL && default_storage_engine=INNODB) have been removed from the db.Connect method to minimize the code changes. The shield-boshrelease will have a working DSN example.

Do the changes look better now? Anything else missing?

**Comment by jhunt** [comment]
Looks pretty good. I will run some more involved tests later to verify that Postgres stuff still works (nothing leads me to believe it _won't_, just want to verify) and then get this merged.

**Comment by karampok** [comment]
If it looks ok, could we merge?
Thx!

**Comment by jhunt** [comment]
Still evaluating.

**Comment by geofffranks** [comment]
I have some concerns with the length of some of your VARCHARs. Limiting them at 255, when they're going to contain the same data as fields from other tables that are TEXTs is going to cause strange issues down the road. 

For example, the `target.endpoint` column is TEXT, and gets copied into `tasks.target_endpoint`, which is a max of 255 characters. Same for the other endpoint, plugin agent, and restore_key related columns. How would you feel about VARCHAR(65535) for those?

**Comment by gogolok** [comment]
Good point. Will change it to VARCHAR(65535)

**Comment by gogolok** [comment]
Ok, MySQL/MariaDB has really some strange limitations. 👎

Although VARCHAR supports the maximum size at 65535 characters, the actual maximum value depends on other columns in the table and character set. Maximum row size is 65535 bytes in MySQL that shared among all columns in the table (except for BLOB and TEXT). Encoding further limits the maximum length of VARCHAR.

**Comment by jhunt** [comment]
Why not use TEXT?

**Comment by geofffranks** [comment]
IIRC mysql didn't allow for TEXT + defaults. Though perhaps no default/ null would get translated properly to an empty string when pulled out via the go library?

**Comment by gogolok** [comment]
MySQL TEXT can't have a default value.

If you don't have enabled strict mode, you can use TEXT DEFAULT ''. Then we would only have an issue with `ALTER TABLE archives ADD COLUMN status TEXT DEFAULT 'valid'`

**Comment by jhunt** [comment]
Columns like `status` don't need to be TEXT; they are more enums than anything else.

Things like `endpoint` on the other hand *do* need to be TEXT, because they are open-ended JSON configuration provided by end users.

**Pull request merged**
