### PR TITLE
Removed deprecated command aliases

### PR DESCRIPTION
**Pull request by thomasmmitchell**
```
ALIASES:
  remove alias, remove-alias, rm alias, remove command alias, rm a, delete alias, politely ask alias to leave
```

### CODE REVIEW

**Comment by thomasmmitchell** [comment]
Closes #302

**Comment by thomasmmitchell** [comment]
One of these days I'll get it right.... hold on a moment.

**Comment by thomasmmitchell** [comment]
I made my fixes, unless you notice anything else

**Comment by thomasmmitchell** [comment]
Or if you have an opinion on what's going and what's staying

**Comment by jhunt** [comment]
LGTM.  Another fine PR, @thomasmmitchell

**Pull request merged**
