### PR TITLE
add Bbr plugin

### PR DESCRIPTION
**Pull request by ramonskie**
added a plugin so shield is able to backup/restore bbr enabled deployments or bosh directors

### CODE REVIEW

**Comment by thomasmmitchell** [comment]
Hey Ramon. I had made a change that got merged to master that caused a file conflict with your branch like... a week ago. I just noticed and I fixed your branch.

**Comment by thomasmmitchell** [comment]
It looks like vendoring still has an issue though

**Comment by ramonskie** [comment]
@thomasmmitchell nto exactly sure what you did
but there is a readme of the bbr plugin that explains how to update the vendor deps

**Comment by thomasmmitchell** [comment]
All I did was pull in the the version of main from master because you had added a newline to the old version that was causing a merge conflict.

**Pull request closed without merging**
